// Generated by CoffeeScript 1.8.0

/*
 * Implementation of History
 */
var getter;

getter = function() {
  return value + 1;
};

Object.defineProperty(Object.prototype, "__defineGetter__", {
  value: getter,
  configurable: true,
  enumerable: false
});
